### ISSUE TITLE
Button added

### ISSUE THREAD

**Issue by rasanderson** [simone-mordue/InferSDGs#3]
Successfully added file upload button. Next main challenge is that the reading of pdf (and text) files is hidden inside a function readtext() rather than directly. Also, the shiny function fileInput can accept multiple files, but it actually returns the list of files (it uploads them to temporary filespace, calling them 0.pdf, 1.pdf etc. It doesn't ask for a folder. So my guess is that either we need to extract the folder name from what is currently in the input$upload slot, or change the readtext() function.

**Comment by simone-mordue** [comment]
Hi Roy,

I think I have the app working now... please could you try running it with two or three random .pdf files and let me know?

Best wishses,
Simone
________________________________
From: Roy Sanderson ***@***.***>
Sent: Friday, May 21, 2021 10:58 AM
To: simone-mordue/InferSDGs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [simone-mordue/InferSDGs] Button added (#3)


⚠ External sender. Take care when opening links or attachments. Do not provide your login details.

Successfully added file upload button. Next main challenge is that the reading of pdf (and text) files is hidden inside a function readtext() rather than directly. Also, the shiny function fileInput can accept multiple files, but it actually returns the list of files (it uploads them to temporary filespace, calling them 0.pdf, 1.pdf etc. It doesn't ask for a folder. So my guess is that either we need to extract the folder name from what is currently in the input$upload slot, or change the readtext() function.

**Comment by rasanderson** [comment]
Hi Simone

Thanks for the update (there were a few notifications from GitHub). I’ll try downloading and checking later this week.

Best wishes
Roy

**Comment by simone-mordue** [comment]
App can now read in text successfully
