### ISSUE TITLE
Does not upload single .pdf files

### ISSUE THREAD

**Issue by simone-mordue** [simone-mordue/InferSDGs#7]
I get an error when uploading a single .pdf files - it works fine when I upload 2 or more. I have found this issue hard to debug but I think it might be to do with the ggplot code section.

**Comment by rasanderson** [comment]
Hi Simone
I think the problem is that you are calculating a mean, so if you upload a single file it will fall over. I've added a dialog box to remind users to upload 2 or more files. Also changed the names from 0.txt or 1.pdf in the graph so that they are now the names of the original documents.
Roy
